<a href="https://colab.research.google.com/github/Deepak-tailor/Data-Analysis/blob/main/Panda2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2026-07-01 16:45:35--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 108.177.11.139, 108.177.11.100, 108.177.11.101, ...
Connecting to drive.google.com (drive.google.com)|108.177.11.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2026-07-01 16:45:35--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 173.194.212.132, 2607:f8b0:400c:c32::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|173.194.212.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    in 0.001s

2026-07-01 16:45:36 (86.2 MB/s) - ‘mckinsey.csv’ saved [83785/83785]

In [3]:
df = pd.read_csv('mckinsey.csv')

In [4]:
df.head(2)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030

In [5]:
df.tail(2)

       country  year  population continent  life_exp     gdp_cap
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [6]:
type(df['country'])

pandas.core.series.Series

In [7]:
se = df['country']

In [8]:
# df[0]

In [9]:
se[0]

'Afghanistan'

In [10]:
df[ : 5]

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [11]:
df.index = list(range(1, len(df) + 1))

In [12]:
df

          country  year  population continent  life_exp     gdp_cap
1     Afghanistan  1952     8425333      Asia    28.801  779.445314
2     Afghanistan  1957     9240934      Asia    30.332  820.853030
3     Afghanistan  1962    10267083      Asia    31.997  853.100710
4     Afghanistan  1967    11537966      Asia    34.020  836.197138
5     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1701     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1702     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1703     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1704     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [13]:
# How do we access data using explicit index?

In [14]:
# df.loc[0]

In [15]:
df.loc[1]

country       Afghanistan
year                 1952
population        8425333
continent            Asia
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [16]:
# Access elements using implicit index

In [17]:
df.iloc[0]

country       Afghanistan
year                 1952
population        8425333
continent            Asia
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [18]:
df.iloc[-1]

country         Zimbabwe
year                2007
population      12311143
continent         Africa
life_exp          43.487
gdp_cap       469.709298
Name: 1704, dtype: object

In [19]:
# df.loc[-1]

In [20]:
len(df)

1704

In [21]:
df.shape[0]

1704

In [22]:
df.loc[len(df)]

country         Zimbabwe
year                2007
population      12311143
continent         Africa
life_exp          43.487
gdp_cap       469.709298
Name: 1704, dtype: object

In [23]:
df.index[-1]

np.int64(1704)

In [24]:
df.loc[1 : 4] # Start and end both are inclusive

       country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710
4  Afghanistan  1967    11537966      Asia    34.020  836.197138

In [25]:
df.iloc[1 : 4] # Start is inclusive but end is exclusive

       country  year  population continent  life_exp     gdp_cap
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710
4  Afghanistan  1967    11537966      Asia    34.020  836.197138

In [26]:
df.iloc[[1, 2, 3, 4]]

       country  year  population continent  life_exp     gdp_cap
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710
4  Afghanistan  1967    11537966      Asia    34.020  836.197138
5  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [27]:
df.loc[[1, 2, 3]]

       country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710

In [28]:
df.reset_index(drop = True, inplace=True)

In [29]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

Adding some data

In [30]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [31]:
len(df)

1704

In [32]:
#df.loc[0]

In [33]:
df.loc[1704] = ['India', 2026, 1400000000, 'Asia', 65, 500]

In [34]:
df.loc[1705] = ['India', 2025, 1400000000, 'Asia', 65, 500]

In [35]:
df.tail(3)

       country  year  population continent  life_exp     gdp_cap
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704     India  2026  1400000000      Asia    65.000  500.000000
1705     India  2025  1400000000      Asia    65.000  500.000000

In [36]:
# Using iloc we can't insert row at a new index, but we can update an existing one.

In [37]:
# df.iloc[1706] = ['India', 2025, 1400000000, 'Asia', 65, 500]

## Deleting Data
- Handling duplicate values

In [38]:
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]
df.loc[len(df)] = ['India', 2025, 1400000000, 'Asia', 65, 500]

In [39]:
df.tail(12)

       country  year  population continent  life_exp     gdp_cap
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704     India  2026  1400000000      Asia    65.000  500.000000
1705     India  2025  1400000000      Asia    65.000  500.000000
1706     India  2025  1400000000      Asia    65.000  500.000000
1707     India  2025  1400000000      Asia    65.000  500.000000
1708     India  2025  1400000000      Asia    65.000  500.000000
1709     India  2025  1400000000      Asia    65.000  500.000000
1710     India  2025  1400000000      Asia    65.000  500.000000
1711     India  2025  1400000000      Asia    65.000  500.000000
1712     India  2025  1400000000      Asia    65.000  500.000000
1713     India  2025  1400000000      Asia    65.000  500.000000
1714     India  2025  1400000000      Asia    65.000  500.000000

In [40]:
df.drop([1714, 1713, 1712])

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1707        India  2025  1400000000      Asia    65.000  500.000000
1708        India  2025  1400000000      Asia    65.000  500.000000
1709        India  2025  1400000000      Asia    65.000  500.000000
1710        India  2025  1400000000      Asia    65.000  500.000000
1711        India  2025  1400000000      Asia    65.000  500.000000

[1712 rows x 6 columns]

In [41]:
df.tail(12)

       country  year  population continent  life_exp     gdp_cap
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704     India  2026  1400000000      Asia    65.000  500.000000
1705     India  2025  1400000000      Asia    65.000  500.000000
1706     India  2025  1400000000      Asia    65.000  500.000000
1707     India  2025  1400000000      Asia    65.000  500.000000
1708     India  2025  1400000000      Asia    65.000  500.000000
1709     India  2025  1400000000      Asia    65.000  500.000000
1710     India  2025  1400000000      Asia    65.000  500.000000
1711     India  2025  1400000000      Asia    65.000  500.000000
1712     India  2025  1400000000      Asia    65.000  500.000000
1713     India  2025  1400000000      Asia    65.000  500.000000
1714     India  2025  1400000000      Asia    65.000  500.000000

In [42]:
df.duplicated() # Boolean array"

0       False
1       False
2       False
3       False
4       False
        ...
1710     True
1711     True
1712     True
1713     True
1714     True
Length: 1715, dtype: bool

In [43]:
sum(df.duplicated())

9

In [44]:
df[df.duplicated()]

     country  year  population continent  life_exp  gdp_cap
1706   India  2025  1400000000      Asia      65.0    500.0
1707   India  2025  1400000000      Asia      65.0    500.0
1708   India  2025  1400000000      Asia      65.0    500.0
1709   India  2025  1400000000      Asia      65.0    500.0
1710   India  2025  1400000000      Asia      65.0    500.0
1711   India  2025  1400000000      Asia      65.0    500.0
1712   India  2025  1400000000      Asia      65.0    500.0
1713   India  2025  1400000000      Asia      65.0    500.0
1714   India  2025  1400000000      Asia      65.0    500.0

In [45]:
df.tail(12)

       country  year  population continent  life_exp     gdp_cap
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704     India  2026  1400000000      Asia    65.000  500.000000
1705     India  2025  1400000000      Asia    65.000  500.000000
1706     India  2025  1400000000      Asia    65.000  500.000000
1707     India  2025  1400000000      Asia    65.000  500.000000
1708     India  2025  1400000000      Asia    65.000  500.000000
1709     India  2025  1400000000      Asia    65.000  500.000000
1710     India  2025  1400000000      Asia    65.000  500.000000
1711     India  2025  1400000000      Asia    65.000  500.000000
1712     India  2025  1400000000      Asia    65.000  500.000000
1713     India  2025  1400000000      Asia    65.000  500.000000
1714     India  2025  1400000000      Asia    65.000  500.000000

In [46]:
# How do we drop these duplicate records: df.drop_duplicates()

In [47]:
df.drop_duplicates()

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2026  1400000000      Asia    65.000  500.000000
1705        India  2025  1400000000      Asia    65.000  500.000000

[1706 rows x 6 columns]

In [48]:
df.drop_duplicates(keep = 'first')

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2026  1400000000      Asia    65.000  500.000000
1705        India  2025  1400000000      Asia    65.000  500.000000

[1706 rows x 6 columns]

In [49]:
df.drop_duplicates(keep = 'last')

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2026  1400000000      Asia    65.000  500.000000
1714        India  2025  1400000000      Asia    65.000  500.000000

[1706 rows x 6 columns]

In [50]:
df.drop_duplicates(keep = False)

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2026  1400000000      Asia    65.000  500.000000

[1705 rows x 6 columns]

In [52]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1710        India  2025  1400000000      Asia    65.000  500.000000
1711        India  2025  1400000000      Asia    65.000  500.000000
1712        India  2025  1400000000      Asia    65.000  500.000000
1713        India  2025  1400000000      Asia    65.000  500.000000
1714        India  2025  1400000000      Asia    65.000  500.000000

[1715 rows x 6 columns]

In [53]:
df.drop_duplicates(subset = ['country'])

                 country  year  population continent  life_exp      gdp_cap
0            Afghanistan  1952     8425333      Asia    28.801   779.445314
12               Albania  1952     1282697    Europe    55.230  1601.056136
24               Algeria  1952     9279525    Africa    43.077  2449.008185
36                Angola  1952     4232095    Africa    30.015  3520.610273
48             Argentina  1952    17876956  Americas    62.485  5911.315053
...                  ...   ...         ...       ...       ...          ...
1644             Vietnam  1952    26246839      Asia    40.412   605.066492
1656  West Bank and Gaza  1952     1030585      Asia    43.160  1515.592329
1668         Yemen, Rep.  1952     4963829      Asia    32.548   781.717576
1680              Zambia  1952     2672000    Africa    42.038  1147.388831
1692            Zimbabwe  1952     3080907    Africa    48.451   406.884115

[142 rows x 6 columns]

##Quiz

In [54]:
data = {'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
        'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
        'C': ['small', 'large', 'large', 'small', 'small', 'large', 'large', 'small'],
        'D': [1, 2, 2, 3, 3, 4, 5, 6]}

DF = pd.DataFrame(data)

print(sum(DF.duplicated(subset=['A', 'B'])))

2

In [56]:
DF

     A      B      C  D
0  foo    one  small  1
1  bar    one  large  2
2  foo    two  large  2
3  bar  three  small  3
4  foo    two  small  3
5  bar    two  large  4
6  foo    one  large  5
7  foo  three  small  6

## Slicing the dataframe
- iloc and loc revisited

In [57]:
# Get first 4 rows from our dataframe using index. (Both inclusive)

In [58]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [59]:
df.iloc[0 : 4] # Here end is exclusive

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138

In [60]:
df.loc[0 : 3] # Here end is also inclusive

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138

In [61]:
# iloc -> end is exclusive

In [62]:
df.iloc[0:5, 0:3]

       country  year  population
0  Afghanistan  1952     8425333
1  Afghanistan  1957     9240934
2  Afghanistan  1962    10267083
3  Afghanistan  1967    11537966
4  Afghanistan  1972    13079460

In [63]:
# df.loc[0:5, 0:3] -> we can't access data like this using loc

In [64]:
df.loc[0:4, 'country' : 'population']

       country  year  population
0  Afghanistan  1952     8425333
1  Afghanistan  1957     9240934
2  Afghanistan  1962    10267083
3  Afghanistan  1967    11537966
4  Afghanistan  1972    13079460

In [65]:
df.head(5)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [66]:
df.loc[0:4, ['country', 'life_exp']]

       country  life_exp
0  Afghanistan    28.801
1  Afghanistan    30.332
2  Afghanistan    31.997
3  Afghanistan    34.020
4  Afghanistan    36.088

In [67]:
# HW:
# df.iloc[[0, 10, 2], [2, 1, 2]]
# df.iloc[0:10:2, :'gdp_cap':2]

## Pandas Inbuilt Operations
- Aggregate Functions

In [68]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [69]:
le = df['life_exp']

In [70]:
# What is avg/mean life expectancy of our dataset?

In [71]:
le.mean()

np.float64(59.509880279883376)

In [72]:
le.sum()

np.float64(102059.44467999999)

In [73]:
# Maximum life expectancy worldwide

In [74]:
le.max()

82.603

In [75]:
le.min()

23.599

In [76]:
# HW: Find the name of country with highest life_exp?

In [77]:
# Find the name of country with highest gdp_cap?

In [78]:
max_gdp = df['gdp_cap'].max()

In [79]:
max_gdp

113523.1329

In [80]:
df['gdp_cap'] == max_gdp

0       False
1       False
2       False
3       False
4       False
        ...
1710    False
1711    False
1712    False
1713    False
1714    False
Name: gdp_cap, Length: 1715, dtype: bool

In [81]:
df[df['gdp_cap'] == max_gdp]

    country  year  population continent  life_exp      gdp_cap
853  Kuwait  1957      212846      Asia    58.033  113523.1329

In [82]:
df[df['gdp_cap'] == max_gdp]['country'].values[0]

'Kuwait'

##Sorting

In [83]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [84]:
# Sort the data wrt life_exp of each country

In [85]:
df.sort_values(by = 'life_exp')

               country  year  population continent  life_exp       gdp_cap
1292            Rwanda  1992     7290203    Africa    23.599    737.068595
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
552             Gambia  1952      284320    Africa    30.000    485.230659
36              Angola  1952     4232095    Africa    30.015   3520.610273
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736
...                ...   ...         ...       ...       ...           ...
1487       Switzerland  2007     7554661    Europe    81.701  37506.419070
695            Iceland  2007      301931    Europe    81.757  36180.789190
802              Japan  2002   127065841      Asia    82.000  28604.591900
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
803              Japan  2007   127467972      Asia    82.603  31656.068060

[1715 rows x 6 columns]

In [86]:
df.sort_values(by = 'life_exp', ascending=False)

               country  year  population continent  life_exp       gdp_cap
803              Japan  2007   127467972      Asia    82.603  31656.068060
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
802              Japan  2002   127065841      Asia    82.000  28604.591900
695            Iceland  2007      301931    Europe    81.757  36180.789190
1487       Switzerland  2007     7554661    Europe    81.701  37506.419070
...                ...   ...         ...       ...       ...           ...
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736
36              Angola  1952     4232095    Africa    30.015   3520.610273
552             Gambia  1952      284320    Africa    30.000    485.230659
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
1292            Rwanda  1992     7290203    Africa    23.599    737.068595

[1715 rows x 6 columns]

In [87]:
# Get year-wise data ascending wrt year (low-high) and for life_expectancy(high-low) for all the countries

In [88]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1710        India  2025  1400000000      Asia    65.000  500.000000
1711        India  2025  1400000000      Asia    65.000  500.000000
1712        India  2025  1400000000      Asia    65.000  500.000000
1713        India  2025  1400000000      Asia    65.000  500.000000
1714        India  2025  1400000000      Asia    65.000  500.000000

[1715 rows x 6 columns]

In [89]:
df.sort_values(['year', 'life_exp'])

           country  year  population continent  life_exp      gdp_cap
0      Afghanistan  1952     8425333      Asia    28.801   779.445314
552         Gambia  1952      284320    Africa    30.000   485.230659
36          Angola  1952     4232095    Africa    30.015  3520.610273
1344  Sierra Leone  1952     2143249    Africa    30.331   879.787736
1032    Mozambique  1952     6446316    Africa    31.286   468.526038
...            ...   ...         ...       ...       ...          ...
1711         India  2025  1400000000      Asia    65.000   500.000000
1712         India  2025  1400000000      Asia    65.000   500.000000
1713         India  2025  1400000000      Asia    65.000   500.000000
1714         India  2025  1400000000      Asia    65.000   500.000000
1704         India  2026  1400000000      Asia    65.000   500.000000

[1715 rows x 6 columns]

In [90]:
df.sort_values(['year', 'life_exp'], ascending = [True, False])

          country  year  population continent  life_exp       gdp_cap
1140       Norway  1952     3327728    Europe     72.67  10095.421720
684       Iceland  1952      147962    Europe     72.49   7267.688428
1080  Netherlands  1952    10381988    Europe     72.13   8941.571858
1464       Sweden  1952     7124673    Europe     71.86   8527.844662
408       Denmark  1952     4334000    Europe     70.78   9692.385245
...           ...   ...         ...       ...       ...           ...
1711        India  2025  1400000000      Asia     65.00    500.000000
1712        India  2025  1400000000      Asia     65.00    500.000000
1713        India  2025  1400000000      Asia     65.00    500.000000
1714        India  2025  1400000000      Asia     65.00    500.000000
1704        India  2026  1400000000      Asia     65.00    500.000000

[1715 rows x 6 columns]

In [91]:
df[df['country'] == "India"]

     country  year  population continent  life_exp      gdp_cap
696    India  1952   372000000      Asia    37.373   546.565749
697    India  1957   409000000      Asia    40.249   590.061996
698    India  1962   454000000      Asia    43.605   658.347151
699    India  1967   506000000      Asia    47.193   700.770611
700    India  1972   567000000      Asia    50.651   724.032527
701    India  1977   634000000      Asia    54.208   813.337323
702    India  1982   708000000      Asia    56.596   855.723538
703    India  1987   788000000      Asia    58.553   976.512676
704    India  1992   872000000      Asia    60.223  1164.406809
705    India  1997   959000000      Asia    61.765  1458.817442
706    India  2002  1034172547      Asia    62.879  1746.769454
707    India  2007  1110396331      Asia    64.698  2452.210407
1704   India  2026  1400000000      Asia    65.000   500.000000
1705   India  2025  1400000000      Asia    65.000   500.000000
1706   India  2025  1400000000      Asia    65.000   500.000000
1707   India  2025  1400000000      Asia    65.000   500.000000
1708   India  2025  1400000000      Asia    65.000   500.000000
1709   India  2025  1400000000      Asia    65.000   500.000000
1710   India  2025  1400000000      Asia    65.000   500.000000
1711   India  2025  1400000000      Asia    65.000   500.000000
1712   India  2025  1400000000      Asia    65.000   500.000000
1713   India  2025  1400000000      Asia    65.000   500.000000
1714   India  2025  1400000000      Asia    65.000   500.000000

Quiz
- How to sort a Pandas dataframe in place based on the values of columns country and population in descending order?

In [92]:
# df.sort_values(['country','population'])

# df.sort_values(['country','population'], inplace=True)

# df.sort_values(['country','population'], inplace=True, ascending=False)

# df.sort_values(['country','population'], inplace=True, ascending=True)

# Ans: 3rd Option

## Concatenation and Merging

In [93]:
# users -> stores the user details - ID and Name of the users

In [94]:
users = pd.DataFrame({'user_id' : [1, 2, 3],
                      'name' : ['Sharadh', 'Rahul', 'Khushali']})

In [95]:
users

   user_id      name
0        1   Sharadh
1        2     Rahul
2        3  Khushali

In [96]:
# msgs -> Stores the messages user have sent - IDs and messages

In [98]:
msgs = pd.DataFrame({'user_id' : [1, 1, 2, 4],
                     'msg' : ['Hmm', 'achha', 'theek hai', 'nice']})

In [99]:
# We can combine these dataframes to form a single dataframe

In [101]:
pd.concat([users, msgs])

   user_id      name        msg
0        1   Sharadh        NaN
1        2     Rahul        NaN
2        3  Khushali        NaN
0        1       NaN        Hmm
1        1       NaN      achha
2        2       NaN  theek hai
3        4       NaN       nice

In [102]:
pd.concat([users, msgs], axis = 1)

   user_id      name  user_id        msg
0      1.0   Sharadh        1        Hmm
1      2.0     Rahul        1      achha
2      3.0  Khushali        2  theek hai
3      NaN       NaN        4       nice

## Merging DataFrames

In [103]:
users

   user_id      name
0        1   Sharadh
1        2     Rahul
2        3  Khushali

In [105]:
msgs

   user_id        msg
0        1        Hmm
1        1      achha
2        2  theek hai
3        4       nice

In [106]:
users.merge(msgs, on = 'user_id')

   user_id     name        msg
0        1  Sharadh        Hmm
1        1  Sharadh      achha
2        2    Rahul  theek hai

In [107]:
# Get all users

In [108]:
users.merge(msgs, on = 'user_id', how = 'left')

   user_id      name        msg
0        1   Sharadh        Hmm
1        1   Sharadh      achha
2        2     Rahul  theek hai
3        3  Khushali        NaN

In [109]:
pd.merge(users, msgs, on = 'user_id', how = 'left')

   user_id      name        msg
0        1   Sharadh        Hmm
1        1   Sharadh      achha
2        2     Rahul  theek hai
3        3  Khushali        NaN

In [110]:
users.merge(msgs, on = 'user_id', how = 'right')

   user_id     name        msg
0        1  Sharadh        Hmm
1        1  Sharadh      achha
2        2    Rahul  theek hai
3        4      NaN       nice