<a href="https://colab.research.google.com/github/Deepak-tailor/Data-Analysis/blob/main/Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2026-06-29 15:53:23--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 142.250.141.138, 142.250.141.139, 142.250.141.101, ...
Connecting to drive.google.com (drive.google.com)|142.250.141.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2026-06-29 15:53:24--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.101.132, 2607:f8b0:4023:c06::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.101.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    in 0.03s

2026-06-29 15:53:25 (2.90 MB/s) - ‘mckinsey.csv’ saved [83785/83785]

In [ ]:
df = pd.read_csv('mckinsey.csv') # storing the data in df
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [ ]:
type(df['country'])

pandas.core.series.Series

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.tail()

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [ ]:
df.shape

(1704, 6)

In [ ]:
df.shape[0]

1704

In [ ]:
### some basic operations on columns

### some basic operations on columns


*   Add a column
*   Delete a Column


*   Rename a column

In [ ]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [ ]:
df[['country', 'population']].head()

       country  population
0  Afghanistan     8425333
1  Afghanistan     9240934
2  Afghanistan    10267083
3  Afghanistan    11537966
4  Afghanistan    13079460

In [18]:
df['country'].head(3)

0    Afghanistan
1    Afghanistan
2    Afghanistan
Name: country, dtype: object

In [19]:
type(df['country'])

pandas.core.series.Series

In [20]:
type(df[['country']])

pandas.core.frame.DataFrame

In [21]:
# Get all the unique countries in which this survey has been conducted?

In [22]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [36]:
df['country'].unique().size

142

In [37]:
len(df['country'].unique())

142

In [38]:
df['country'].nunique()

142

In [39]:
 # For each unique countries how many times this survey has been conducted?

In [40]:
 # Get all the unique values and their frequencies

In [41]:
df['country'].value_counts() # This gives us output in decreasing order of frequencies

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [23]:
# Rename a column

In [24]:
df.head(2)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030

In [25]:
df.rename({'country': 'Country', 'year': 'Year'}, axis =1)

          Country  Year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [26]:
df.head(2)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030

In [27]:
df.rename({'country': 'Country', 'year': 'Year'})

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [28]:
df.head(2)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030

In [ ]:
#Hw : do these changes in place

In [29]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [30]:
# Name of a column can coincide with the name of a method

In [31]:
df.shape

(1704, 6)

In [32]:
# A column name can have white space in it

In [33]:
# df.first name

In [34]:
#A column name can start with a number

In [42]:
# df.lstname

In [43]:
a1 = 'Rahul'

In [44]:
# 1a = 'Rahul'

Drop a Column

In [45]:
df.head(3)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710

In [47]:
df.drop('continent', axis = 1, inplace = True)

In [48]:
df.head(2)

       country  year  population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030

In [50]:
df.drop(columns = ['country', 'year'])

      population  life_exp     gdp_cap
0        8425333    28.801  779.445314
1        9240934    30.332  820.853030
2       10267083    31.997  853.100710
3       11537966    34.020  836.197138
4       13079460    36.088  739.981106
...          ...       ...         ...
1699     9216418    62.351  706.157306
1700    10704340    60.377  693.420786
1701    11404948    46.809  792.449960
1702    11926563    39.989  672.038623
1703    12311143    43.487  469.709298

[1704 rows x 3 columns]

Creating new column

In [51]:
df.head(2)

       country  year  population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030

In [52]:
df['year + 7'] = df['year']+ 7

In [53]:
df.head(3)

       country  year  population  life_exp     gdp_cap  year + 7
0  Afghanistan  1952     8425333    28.801  779.445314      1959
1  Afghanistan  1957     9240934    30.332  820.853030      1964
2  Afghanistan  1962    10267083    31.997  853.100710      1969

In [54]:
df['gdp'] = df['population'] * df['gdp_cap']

In [55]:
df.head(2)

       country  year  population  life_exp     gdp_cap  year + 7           gdp
0  Afghanistan  1952     8425333    28.801  779.445314      1959  6.567086e+09
1  Afghanistan  1957     9240934    30.332  820.853030      1964  7.585449e+09

In [56]:
df.shape

(1704, 7)

In [57]:
df['rank'] = [i for i in range(1, df.shape[0] + 1)]

In [58]:
df.head(3)

,country,year,population,life_exp,gdp_cap,year + 7,gdp,rank
0,Afghanistan,1952,8425333,28.801,779.445314,1959,6.567086e+09,1
1,Afghanistan,1957,9240934,30.332,820.853030,1964,7.585449e+09,2
2,Afghanistan,1962,10267083,31.997,853.100710,1969,8.758856e+09,3

In [60]:
df.drop(columns = ['year + 7', 'gdp', 'rank'], inplace = True)

In [61]:
df.head(3)

       country  year  population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710

Quiz
Given a dataframe consisting of 5 columns, which is the correct code to drop the 3rd column from the start?

In [72]:
# df.drop(df.columns[-3], axis=1)

# df.drop(df.columns[3], axis=1)

# df.drop(df.columns[-3], axis=0)

# df.drop(df.columns[3], axis=0)

# Ans: Option 1

In [73]:
df.drop(df.columns[-3], axis=1)

          country  year  life_exp     gdp_cap
0     Afghanistan  1952    28.801  779.445314
1     Afghanistan  1957    30.332  820.853030
2     Afghanistan  1962    31.997  853.100710
3     Afghanistan  1967    34.020  836.197138
4     Afghanistan  1972    36.088  739.981106
...           ...   ...       ...         ...
1699     Zimbabwe  1987    62.351  706.157306
1700     Zimbabwe  1992    60.377  693.420786
1701     Zimbabwe  1997    46.809  792.449960
1702     Zimbabwe  2002    39.989  672.038623
1703     Zimbabwe  2007    43.487  469.709298

[1704 rows x 4 columns]

Some operations on rows

In [74]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [75]:
df.head(3)

       country  year  population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710

In [62]:
df.shape

(1704, 5)

In [76]:
df.shape[0] + 1

1705

In [77]:
df.index = list(range(1, df.shape[0] + 1)) # Creates custom index -> explicit index

In [ ]:
# Explicit indexing: The custom indexing given by us
# Implicit indexing: Python style of indexing -> 0 based indexing

In [78]:
df.index = np.arange(1, df.shape[0] + 1, dtype = float)

In [79]:
df

            country  year  population  life_exp     gdp_cap
1.0     Afghanistan  1952     8425333    28.801  779.445314
2.0     Afghanistan  1957     9240934    30.332  820.853030
3.0     Afghanistan  1962    10267083    31.997  853.100710
4.0     Afghanistan  1967    11537966    34.020  836.197138
5.0     Afghanistan  1972    13079460    36.088  739.981106
...             ...   ...         ...       ...         ...
1700.0     Zimbabwe  1987     9216418    62.351  706.157306
1701.0     Zimbabwe  1992    10704340    60.377  693.420786
1702.0     Zimbabwe  1997    11404948    46.809  792.449960
1703.0     Zimbabwe  2002    11926563    39.989  672.038623
1704.0     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.index

In [66]:
# df[1] -> used to access a column

In [67]:
df[ : 5] # slice of a dataframe

       country  year  population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [68]:
sample = df.head()

In [69]:
sample.index = ['a', 'b', 'c', 'd', 'e']

In [70]:
sample

       country  year  population  life_exp     gdp_cap
a  Afghanistan  1952     8425333    28.801  779.445314
b  Afghanistan  1957     9240934    30.332  820.853030
c  Afghanistan  1962    10267083    31.997  853.100710
d  Afghanistan  1967    11537966    34.020  836.197138
e  Afghanistan  1972    13079460    36.088  739.981106

In [71]:
sample[ : 2]

       country  year  population  life_exp     gdp_cap
a  Afghanistan  1952     8425333    28.801  779.445314
b  Afghanistan  1957     9240934    30.332  820.853030

In [80]:
#df['country']

In [81]:
ser = df['country']

In [82]:
ser.head(18)

1.0     Afghanistan
2.0     Afghanistan
3.0     Afghanistan
4.0     Afghanistan
5.0     Afghanistan
6.0     Afghanistan
7.0     Afghanistan
8.0     Afghanistan
9.0     Afghanistan
10.0    Afghanistan
11.0    Afghanistan
12.0    Afghanistan
13.0        Albania
14.0        Albania
15.0        Albania
16.0        Albania
17.0        Albania
18.0        Albania
Name: country, dtype: object

In [83]:
ser[12]

'Afghanistan'

In [84]:
ser[13]

'Albania'

loc vs iloc

loc : explicit indexing

iloc : implicit indexing

In [96]:
df.index[0] # It returns corresponding explicit index of implicit index

np.float64(1.0)

In [97]:
sample.index[0]

'a'

In [98]:
sample.index[1]

'b'

In [99]:
df.head()

         country  year  population  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333    28.801  779.445314
2.0  Afghanistan  1957     9240934    30.332  820.853030
3.0  Afghanistan  1962    10267083    31.997  853.100710
4.0  Afghanistan  1967    11537966    34.020  836.197138
5.0  Afghanistan  1972    13079460    36.088  739.981106

In [85]:
ser[5 :13] # implicit index is being used here

/tmp/ipykernel_12320/577841598.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  ser[5 :13] # implicit index is being used here

5.0     Afghanistan
6.0     Afghanistan
7.0     Afghanistan
8.0     Afghanistan
9.0     Afghanistan
10.0    Afghanistan
11.0    Afghanistan
12.0    Afghanistan
13.0        Albania
Name: country, dtype: object

In [86]:
df.iloc[0] # Implicit indexing

country       Afghanistan
year                 1952
population        8425333
life_exp           28.801
gdp_cap        779.445314
Name: 1.0, dtype: object

In [87]:
df.loc[1] #Explicit index

country       Afghanistan
year                 1952
population        8425333
life_exp           28.801
gdp_cap        779.445314
Name: 1.0, dtype: object

In [100]:
#df.loc[0]

In [101]:
df.iloc[-1]

country         Zimbabwe
year                2007
population      12311143
life_exp          43.487
gdp_cap       469.709298
Name: 1704.0, dtype: object

In [89]:
# slicing using loc and iloc

In [90]:
df.head()

         country  year  population  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333    28.801  779.445314
2.0  Afghanistan  1957     9240934    30.332  820.853030
3.0  Afghanistan  1962    10267083    31.997  853.100710
4.0  Afghanistan  1967    11537966    34.020  836.197138
5.0  Afghanistan  1972    13079460    36.088  739.981106

In [102]:
#df.loc[-1]

In [103]:
# Slicing using loc and iloc

In [104]:
df.head()

         country  year  population  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333    28.801  779.445314
2.0  Afghanistan  1957     9240934    30.332  820.853030
3.0  Afghanistan  1962    10267083    31.997  853.100710
4.0  Afghanistan  1967    11537966    34.020  836.197138
5.0  Afghanistan  1972    13079460    36.088  739.981106

In [92]:
# when we slice using loc, both start and end index are inclusive

In [94]:
df.loc[1:3]

         country  year  population  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333    28.801  779.445314
2.0  Afghanistan  1957     9240934    30.332  820.853030
3.0  Afghanistan  1962    10267083    31.997  853.100710

In [95]:
df.iloc[1:3]

         country  year  population  life_exp    gdp_cap
2.0  Afghanistan  1957     9240934    30.332  820.85303
3.0  Afghanistan  1962    10267083    31.997  853.10071

In [105]:
df.head(4)

         country  year  population  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333    28.801  779.445314
2.0  Afghanistan  1957     9240934    30.332  820.853030
3.0  Afghanistan  1962    10267083    31.997  853.100710
4.0  Afghanistan  1967    11537966    34.020  836.197138

In [106]:
df.iloc[1:3]

         country  year  population  life_exp    gdp_cap
2.0  Afghanistan  1957     9240934    30.332  820.85303
3.0  Afghanistan  1962    10267083    31.997  853.10071

In [107]:
# df.loc[9::-3]

# 1. rows 0, 3, 6, 9, in this order

# 2. rows 9, 6, 3, 0 in this order

# 3. None of these

# Ans: 2nd option is correct

In [108]:
# We can use a column as an index

In [109]:
temp = df.set_index('country')

In [110]:
temp

             year  population  life_exp     gdp_cap
country
Afghanistan  1952     8425333    28.801  779.445314
Afghanistan  1957     9240934    30.332  820.853030
Afghanistan  1962    10267083    31.997  853.100710
Afghanistan  1967    11537966    34.020  836.197138
Afghanistan  1972    13079460    36.088  739.981106
...           ...         ...       ...         ...
Zimbabwe     1987     9216418    62.351  706.157306
Zimbabwe     1992    10704340    60.377  693.420786
Zimbabwe     1997    11404948    46.809  792.449960
Zimbabwe     2002    11926563    39.989  672.038623
Zimbabwe     2007    12311143    43.487  469.709298

[1704 rows x 4 columns]

In [111]:
temp.loc['Afghanistan']

             year  population  life_exp     gdp_cap
country
Afghanistan  1952     8425333    28.801  779.445314
Afghanistan  1957     9240934    30.332  820.853030
Afghanistan  1962    10267083    31.997  853.100710
Afghanistan  1967    11537966    34.020  836.197138
Afghanistan  1972    13079460    36.088  739.981106
Afghanistan  1977    14880372    38.438  786.113360
Afghanistan  1982    12881816    39.854  978.011439
Afghanistan  1987    13867957    40.822  852.395945
Afghanistan  1992    16317921    41.674  649.341395
Afghanistan  1997    22227415    41.763  635.341351
Afghanistan  2002    25268405    42.129  726.734055
Afghanistan  2007    31889923    43.828  974.580338

In [112]:
# How to reset index back to integers -> 0 based indexing

In [113]:
df

            country  year  population  life_exp     gdp_cap
1.0     Afghanistan  1952     8425333    28.801  779.445314
2.0     Afghanistan  1957     9240934    30.332  820.853030
3.0     Afghanistan  1962    10267083    31.997  853.100710
4.0     Afghanistan  1967    11537966    34.020  836.197138
5.0     Afghanistan  1972    13079460    36.088  739.981106
...             ...   ...         ...       ...         ...
1700.0     Zimbabwe  1987     9216418    62.351  706.157306
1701.0     Zimbabwe  1992    10704340    60.377  693.420786
1702.0     Zimbabwe  1997    11404948    46.809  792.449960
1703.0     Zimbabwe  2002    11926563    39.989  672.038623
1704.0     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [114]:
df.reset_index()

       index      country  year  population  life_exp     gdp_cap
0        1.0  Afghanistan  1952     8425333    28.801  779.445314
1        2.0  Afghanistan  1957     9240934    30.332  820.853030
2        3.0  Afghanistan  1962    10267083    31.997  853.100710
3        4.0  Afghanistan  1967    11537966    34.020  836.197138
4        5.0  Afghanistan  1972    13079460    36.088  739.981106
...      ...          ...   ...         ...       ...         ...
1699  1700.0     Zimbabwe  1987     9216418    62.351  706.157306
1700  1701.0     Zimbabwe  1992    10704340    60.377  693.420786
1701  1702.0     Zimbabwe  1997    11404948    46.809  792.449960
1702  1703.0     Zimbabwe  2002    11926563    39.989  672.038623
1703  1704.0     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 6 columns]

In [115]:
df.reset_index(drop = True)

          country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [116]:
df.head(2)

         country  year  population  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333    28.801  779.445314
2.0  Afghanistan  1957     9240934    30.332  820.853030

In [117]:
df.reset_index(drop = True, inplace = True)

In [118]:
df

          country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]